### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by fingolfin500** [pupil-labs/pyuvc#11]
I get the following error when trying to build on Windows:

![capture](https://cloud.githubusercontent.com/assets/5487401/12237810/80c1ad7a-b878-11e5-9f55-68957a819f9c.PNG)

**Comment by fneitzel** [comment]
I got the same error in Ubuntu:
After executing

cythonize uvc.pyx

it worked.

**Comment by mkassner** [comment]
solved for windows please see latest release.
