### ISSUE TITLE
"could not initialize" when requesting device_list()

### ISSUE THREAD

**Issue by tschneid** [pupil-labs/pyuvc#13]
Hi, 

I'm trying to run the pupil app in a docker container. I installed `libuvc` from [pupil-labs/libuvc](https://github.com/pupil-labs/libuvc) and `pyuvc` from this repository.
However, I get the following error when running the example:
```shell
$ python example.py

ERROR:uvc:could not initialize
None
Traceback (most recent call last):
  File "example.py", line 13, in <module>
    cap = uvc.Capture(dev_list[0]['uid'])
TypeError: 'NoneType' object has no attribute '__getitem__'
```

The same in the python console:
```
>>> import logging
>>> import uvc
>>> logger = logging.getLogger('uvc').addHandler(logging.StreamHandler())
>>> devices = uvc.device_list()
could not initialize
```

The `could not initialize` error comes from https://github.com/pupil-labs/pyuvc/blob/master/uvc.pyx#L282. 

I passed the X socket and the `/dev/video*` devices to the docker container, so I have no problem viewing the camera image with e.g. `vlc`:
```shell
$ cvlc v4l2:///dev/video1
```
Might be related to pupil-labs/pupil#157.

Any ideas on this?

**Comment by mkassner** [comment]
We dont use v4l2 instead we need direct access to the usb devices. please the permissions part in the project readme.

**Comment by tschneid** [comment]
I see! Added `--privileged -v /dev/bus/usb:/dev/bus/usb` to the docker options and it works.
Thanks @mkassner!
