### ISSUE TITLE
doesn't enumerate v4l2loopback device

### ISSUE THREAD

**Issue by avilleret** [pupil-labs/pyuvc#14]
I'm using [v4l2loopback](https://github.com/umlaeute/v4l2loopback) to send video across application.

I have : 

~~~~
$ v4l2-ctl --list-device
Laptop_Integrated_Webcam_2HDM (usb-0000:00:1a.0-1.4):
        /dev/video0

Dummy video device (0x0000) (v4l2loopback:0):
        /dev/video1

Dummy video device (0x0001) (v4l2loopback:1):
        /dev/video2
~~~~
 
and I can open and view the stream in VLC (on /dev/video1)

but `example.py` doesn't enumerates v4l2loopback devices.
Here is the [log](https://gist.github.com/avilleret/889c1e8825ae22ff9e03).

How can I use `v4l2loopback` device with `pyuvc` ?

The stream comes from a raspberry pi over the lan, and gstreamer push it on v4l2loopback device.
That works but I would like to access the stream in Python.

**Comment by mkassner** [comment]
You wont be able to use anything other than usb devices from pyuvc. But you could try https://github.com/pupil-labs/pyv4l2 . Its very similar but uses v4l2 instead of libuvc.

**Comment by avilleret** [comment]
that sounds pretty obvious... 
thanks for opening my eyes !
