### ISSUE TITLE
[ERROR] uvc : Could not init '...'!

### ISSUE THREAD

**Issue by swilmet-ucl** [pupil-labs/pyuvc#15]
When I run the pupil capture application, I get the following errors:

```
WORLD Process [ERROR] uvc : Could not init 'Auto Exposure Mode'!
WORLD Process [ERROR] uvc : Could not init 'Auto Exposure Priority'!
WORLD Process [ERROR] uvc : Could not init 'Absolute Exposure Time'!
WORLD Process [ERROR] uvc : Could not init 'Auto Focus'!
WORLD Process [ERROR] uvc : Could not init 'Absolute Focus'!
WORLD Process [ERROR] uvc : Could not init 'Zoom absolute control'!
WORLD Process [ERROR] uvc : Could not init 'Pan control'!
WORLD Process [ERROR] uvc : Could not init 'Tilt control'!
WORLD Process [ERROR] uvc : Could not init 'Backlight Compensation'!
WORLD Process [ERROR] uvc : Could not init 'Brightness'!
WORLD Process [ERROR] uvc : Could not init 'Contrast'!
WORLD Process [ERROR] uvc : Could not init 'Gain'!
WORLD Process [ERROR] uvc : Could not init 'Power Line frequency'!
WORLD Process [ERROR] uvc : Could not init 'Saturation'!
WORLD Process [ERROR] uvc : Could not init 'Sharpness'!
WORLD Process [ERROR] uvc : Could not init 'White Balance temperature'!
WORLD Process [ERROR] uvc : Could not init 'White Balance temperature,Auto'!
```

I'm on Linux (Fedora), with pyuvc 0.5 (the latest version).

Can you also reproduce that problem?

**Comment by swilmet-ucl** [comment]
I see in the upstream libuvc the commit f511675 "Fix control functions for processors and other devices". It looks like an interesting bug fix, that could be related to the problem here. However when I rebase the pupil-labs's bandwidth_fix branch on top of the upstream master, there is a conflict.

**Comment by cpicanco** [comment]
Well, I have opened some issues related to this one... with different
cameras, so yes, it **is** reproducible

**Comment by cpicanco** [comment]
Ubuntu 14.04

C615
#3 

C525
#6

**Comment by mkassner** [comment]
@saki4510t fixed this just now with https://github.com/pupil-labs/libuvc/commit/900435183778f4a94a4197214166392e74e7edad please updated libuvc and test.

**Comment by saki4510t** [comment]
Hi,
This issue came from libuvc just expected the interface number of camera control interface is always zero. This does not meet UVC specification because

1.  host needs to send interface number of camera control interface as low byte of `wIndex` when sending camera control request.
2. some camera has non-zero interface number for camera control interface, ex. my C525 returns `2`.

I also send pull-request to original libuvc.
saki

**Comment by mkassner** [comment]
@saki4510t fixed this please update libuvc with the latest master branch and it will work.

**Comment by swilmet-ucl** [comment]
Thanks. I confirm it's fixed for me.
