### ISSUE TITLE
pyuvc on windows

### ISSUE THREAD

**Issue by flecheria** [pupil-labs/pyuvc#2]
I've modified the code on setup.py in this way

```
elif platform.system() == 'Windows':
    try:
        tj_lib = 'C:/libjpeg-turbo-gcc/lib/libturbojpeg.a'
    except IndexError:
        raise Exception("Please install libturbojpeg")
```

I ran _python setup.py install_ (i test locally and globally) from the Visual C++ 2008 64-bit Command Prompt of the python package but it gives me this error:
![error_pyuvc](https://cloud.githubusercontent.com/assets/266848/8051318/4e8657ea-0e7b-11e5-9eff-eec7f2c184d9.jpg)

Have you any suggestion? I think is a problem based on the different paths between the Microsoft compiler for VisualStudio and the free version for python...

**Comment by mkassner** [comment]
I m pretty sure this can be tracked down to:

https://github.com/pupil-labs/pyuvc/blob/master/cuvc.pxd#L11

we need to put in a IF ELSE to get the windows equivalent include here.

**Comment by mkassner** [comment]
This issue is related to this: https://github.com/ktossell/libuvc/issues/12

**Comment by flecheria** [comment]
I don't get it. Can you be more specific? Or better, have yopu an example?
Thanks

**Comment by practisebody** [comment]
I just managed to setup pyuvc on my Win7. What I did: 1) installed pthread for Windows(https://sourceware.org/pthreads-win32/), 2) Solution One to solve libusb issue (ktossell/libuvc#12), 3) install turbojepg, make sure it's vc/vc64 version (http://sourceforge.net/projects/libjpeg-turbo/files/) 4) installed libuvc (build a .lib)

Not sure whether all these steps is necessary, maybe some of them are redundant, I was just exploring around.

As to "sys/time.h", I simply manually changed to "time.h". (And maybe replace "libusb-1.0" by "libusb", I forgot the details).

For step 4), I changed two lines in CMakelist.txt to:

set(LIBUSB_LIBRARY_NAMES "libusb-1.0.lib")
find_path(LIBUSB_INCLUDE_DIR libusb/libusb.h
	PATHS "C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/include")

Also use the following code for setup.py:
elif platform.system() == 'Windows':
    try:
        tj_lib = 'C:/libjpeg-turbo64/lib/turbojpeg.lib'
    except IndexError:
        raise Exception("Please install libturbojpeg")
    include_dirs = ['C:/libjpeg-turbo64/include/']
    libs = ['pthreadVC2','libusb-1.0']

Hooray! Now uvc is correctly installed!
HOWEVER, seems it can't get connected to the webcam I have. Maybe it's a problem with libusb. I'm working on it.
Hope this will be useful and let me know if there is anything unclear!

PS everything in x64, but not sure if this is necessary or not.
PPS If you get an "DLL load failed", check if all the .dll files are in the right place (C:\Windows\System32 and/or C:\Windows\SysWOW64).

**Comment by flecheria** [comment]
The code on setup.py is very helpful. 
I compile correctly a modified version of libusb with the patches. Also the libuvc seems work but I'm not an expert. I will try some tests this weekend. Im' studying some cython to make the IF ELSE statment.

In the meantime I have a couple of questions:
- where do you "simply manually changed from "sys/time.h" to "time.h"?
- when do you compile libuvc how solved the jpeg finding? Can I insert the path on a new find_path inside the CMake?
Thanks for your post

**Comment by practisebody** [comment]
@flecheria My solutions:
- because the compile error in your screenshot says: "uvc.c can't find sys/time.h" so I open uvc.c in pyuvc, search for "sys/time.h" and replace it by "time.h"
- I didn't notice that but I tried to rebuild it with JPEG support. First uncomment those lines in CMakeLists.txt, then add one line above them:

> set(JPEG_INCLUDE_DIR "C:/libjpeg-turbo64/include") # where you installed your turbojpeg
When you are trying to build the solution there will be an error in line 173 of frame-mjpeg.c, because of trying to add a void* with integer, you'll need cast out->data to char* so the modified line will look like:

> unsigned char *buffer[1] = { (char*)out->data + lines_read * out->step };

If you encounter any link error, just add those missing libraries using VS.

-----
But my problem is still there, 
> Exception: Can't open stream control: Error:'Operation not supported.'.

@mkassner Could you give me a little hint?

**Comment by mkassner** [comment]
@MichaelBarz I think you got this to run, right?

**Comment by MichaelBarz** [comment]
No, I'm, still working on that.

**Comment by mmyfreelife** [comment]
Dear all:

I compile libuvc on windows 7 64 bit, it went well without any error.
However, I could only get a libuvc,dll, and no *.lib is available. Is it
normal? Thanks in dvance.

Best
                                                      freelife

**Comment by MichaelBarz** [comment]
Hi, I guess that the build configuration builds a shared library only. You might try to configure a static build.
Could you successfully access a camera with your build?

Best Michael

**Comment by mkassner** [comment]
This is solved now. Please see latest release.
