### ISSUE TITLE
Semantic Versioning - `v0.9.1` and not `v0.91` (?)

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pyuvc#28]
Shouldn't the version be `v0.9.1` and not `v0.91`? 

I have a Windows 10 wheel ready for release - but want to make sure that version number remain consistent and compliant with SemVer before making the release. 

The following would need to be changed if this is the case:
- https://github.com/pupil-labs/pyuvc/blob/master/setup.py#L65 
- https://github.com/pupil-labs/pyuvc/blob/master/uvc.pyx#L79

And assertion of version would need to be changed in Pupil source code if updated:
- https://github.com/pupil-labs/pupil/blob/950d8ba005cdda92689b2fd1ccd25696c5c6ccb6/pupil_src/shared_modules/video_capture/uvc_backend.py#L19

**Comment by mkassner** [comment]
thanks fixed.
