### ISSUE TITLE
Won't compile on MacOS Sierra

### ISSUE THREAD

**Issue by jorelllinsangan** [pupil-labs/pyuvc#30]
Hi, 

I'm currently trying to install pyuvc using this fork [](https://github.com/CarlosRDomin/pyuvc).

Running `python setup.y install` gives me this error. 

```
wpa-1-211:pyuvc$ python setup.py install
running install
running build
running build_ext
building 'uvc' extension
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include -I/usr/local/opt/jpeg-turbo/include/ -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c uvc.c -o build/temp.macosx-10.6-intel-2.7/uvc.o
uvc.c:459:10: fatal error: 'libusb-1.0/libusb.h' file not found
#include "libusb-1.0/libusb.h"
         ^
1 error generated.
error: command '/usr/bin/clang' failed with exit status 1
```

I couldn't find anything online to help me fix this issue. I'm hoping you guys have some answers. Thank you!

**Comment by mkassner** [comment]
Hi,

this means the libusb is not installed or cannot be found.

**Comment by jorelllinsangan** [comment]
I have it installed. The main issue is it can't find it. So my question is would you guys be able to offer help in order for pyuvc to locate libusb.

**Comment by mkassner** [comment]
if you installed libusb with homebrew. Please check using brew doctor and also do brew link libusb

**Comment by Windsooon** [comment]
To anyone who also meets this problem, Here is a solution on macOS 10.14.1, When you run
```
make && sudo make install
```

If you get 

`fatal error: 'libusb-1.0/libusb.h' file not found`

Try copy the libusb-1.0 to the include dir like this:

`cp -r /usr/local/include/libusb-1.0 path_to/libuvc/build/include/`

After that, try run make && sudo make install again. If you see error like:

`library not found for -lusb-1.0`

run 

`make LIBRARY_PATH=/usr/local/lib && make install
`
