### ISSUE TITLE
capture initialization failed

### ISSUE THREAD

**Issue by itayse** [pupil-labs/pyuvc#32]
Hi All,
Just received my Pupil Labs eye tracking camera, seems to have a problem with both the world and eye tracking camera.
Pupil capture environment recognize both the eye tracker and the pupil camera within the selection menu, still I’m getting the following message when I try to choose on of the cameras.
“The camera selected is already in use or blocked.”
Under capture source I can see “capture initialization failed”.

When I try to initiate the eye tracker I receive "init failed. capture started in ghost mode. No images will be supplied".

I’m Working with:
1.	Logitech C920 (interface 2)
2.	Pupil Cam1 ID0 (interface 0)
3.	Running Python 3.5 (64 bit) on windows 10

Tried already - 
1.	Updated the latest windows UVC
https://github.com/pupil-labs/pyuvc/blob/master/WINDOWS_USER.md
*didn’t find a link for uvc-0.7.2-cp35-cp35m-win_amd64.whl, assumed that this is the relevant one - uvc-0.10-cp35-cp35m-win_amd64.whl

2. Re-verified that both cameras are working with libusbk drivers under device manager
![image](https://cloud.githubusercontent.com/assets/27953205/25333235/2435de50-28f2-11e7-8c38-1c4651a525af.png)

There were several threads on this issue, but wasn’t solved
https://github.com/pupil-labs/pupil/issues/681
https://github.com/pupil-labs/pupil/issues/603

Any thoughts on this? 
Many thanks
Itay

**Comment by mkassner** [comment]
This usually this means that a (zombi) process is still holding a camera.

**Comment by itayse** [comment]
First thanks for your prompt response here.

It is really strange, I've restarted several times already.
 also tried now to find the zombi process with no success - 
https://superuser.com/questions/335116/finding-out-which-app-is-using-the-webcam

Still the problem persists, it finds both camera, but can't initiate them
![image](https://cloud.githubusercontent.com/assets/27953205/25336963/7a6f30d6-2902-11e7-8f94-9cf23fec208a.png)

Any other direction worth looking into?

Thanks again

**Comment by itayse** [comment]
Just making sure - this is the most update file to install?
uvc-0.10-cp35-cp35m-win_amd64.whl

thx

**Comment by itayse** [comment]
Resolved the issue. was a problem with the libusbk driver version.

Eye tracker is now working, world camera is still an issue, but a different one (shows only white, but apparently this results from different issue)

Thanks for the help

**Comment by itayse** [comment]
closed

**Comment by itayse** [comment]
Fixes #32

**Comment by itayse** [comment]
close #32

**Comment by gmierz** [comment]
Hi @itayse, I'm also having this issue. Do you know which libusbK version ended up working for you?

**Comment by XandeUlsonQMedia** [comment]
Hello, how did you solve the problem?

Is there any place where i can find this driver version @itayse ? I am having the same problem with my camera, it says that is blocked ou being used by another software.

Thanks
