### ISSUE TITLE
Access to camera settings

### ISSUE THREAD

**Issue by gterren** [pupil-labs/pyuvc#33]
Hi, 

I am using pyuvc lib in order to access to camera settings. I could not figure it out by myself yet. Can you give some hints for doing this?

Regards,
Guille

**Comment by cpicanco** [comment]
What camera you are trying to access? I know it may sound obvious, but is
it UVC compliant?

**Comment by Guille129** [comment]
Yes, it is. It should be able to fine tune these parameters: Brightness, Contrast, Saturation, Hue, Sharpness, Gamma, White balance, Backlight Contrast, Exposure.

Thank you for your help!
Guille

Here it is link: [http://www.elpcctv.com/full-hd-usb-camera-module-1080p-usb20-ov2710-color-sensor-support-mjpeg-with-36mm-lens-p-203.html](url)

**Comment by cpicanco** [comment]
Hi, I have a working ELP-* camera. So, your camera should also work. Did you tried the example.py? 

https://github.com/pupil-labs/pyuvc/blob/master/example.py

**Comment by Guille129** [comment]
example.py works fine. 

My problem is that I cannot see how to adjust exposure by libuvc settings.

Do you have any example for doing that or command to modify the settings?

Many thanks!
Guille

**Comment by cpicanco** [comment]
Humm... no sorry. I would recommend you to take a look at the pupil implementation:

https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/video_capture/uvc_backend.py

**Comment by Guille129** [comment]
That should work. Thank you!

**Comment by harsh-lodha** [comment]
Hi @gterren @cpicanco ,
How exactly did you adjust exposure ? Is the uvc_backend file need to be added in installation files ? Kindly help.
Thanks,
Hari

**Comment by gterren** [comment]
Here is the script I wrote: https://github.com/gterren/girasol_machine/blob/main/thread_visible.py

check __check_mode() function.

**Comment by harsh-lodha** [comment]
Hey @gterren , I see all the system calls are in linux . Do you know any way to do this in windows ?

**Comment by gterren** [comment]
I do not use windows. That's all I have!

**Comment by papr** [comment]
Please see this modified version of the repository's example:
```py
import uvc
import logging

logging.basicConfig(level=logging.INFO)

dev_list = uvc.device_list()
print(dev_list)
cap = uvc.Capture(dev_list[0]["uid"])  # init first device

# create a dictionary that maps control names to the actual control objects
controls_dict = dict([(c.display_name, c) for c in cap.controls])

for name, control in controls_dict.items():
    # the `.value` property contains the current value and can be used to set a new value
    print(name, "- current value:" control.value)
    print(name, "- minimum value:" control.min_val)
    print(name, "- maximum vlue:" control.max_val)
```
