### ISSUE TITLE
pyuvc wont compile

### ISSUE THREAD

**Issue by matiarj** [pupil-labs/pyuvc#34]
sudo pip3 install git+https://github.com/pupil-labs/pyuvc
The directory '/home/skellis/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/skellis/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+https://github.com/pupil-labs/pyuvc
  Cloning https://github.com/pupil-labs/pyuvc to /tmp/pip-_sxtiiuy-build
Installing collected packages: uvc
  Running setup.py install for uvc ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-_sxtiiuy-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-w_hs0c2t-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'uvc' extension
    creating build
    creating build/temp.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include/python3.5m -c uvc.c -o build/temp.linux-x86_64-3.5/uvc.o
    In file included from /usr/lib/python3/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                     from /usr/lib/python3/dist-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /usr/lib/python3/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from uvc.c:515:
    /usr/lib/python3/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    uvc.c: In function ‘__pyx_f_3uvc_7Capture__enumerate_controls’:
    uvc.c:17297:26: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_input_terminal = uvc_get_input_terminals(__pyx_v_self->devh);
                              ^
    uvc.c:17306:27: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_output_terminal = uvc_get_output_terminals(__pyx_v_self->devh);
                               ^
    uvc.c:17315:27: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_processing_unit = uvc_get_processing_units(__pyx_v_self->devh);
                               ^
    uvc.c:17324:26: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_extension_unit = uvc_get_extension_units(__pyx_v_self->devh);
                              ^
    uvc.c: In function ‘__pyx_f_3uvc_7Capture__enumerate_formats’:
    uvc.c:17962:23: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_format_desc = uvc_get_format_descs(__pyx_v_self->devh);
                           ^
    uvc.c: At top level:
    uvc.c:20423:13: warning: ‘__pyx_f_3uvc_on_status_update’ defined but not used [-Wunused-function]
     static void __pyx_f_3uvc_on_status_update(CYTHON_UNUSED enum uvc_status_class __pyx_v_status_class, CYTHON_UNUSED int __pyx_v_event, CYTHON_UNUSED int __pyx_v_selector, CYTHON_UNUSED enum uvc_status_attribute __pyx_v_status_attribute, CYTHON_UNUSED void *__pyx_v_data, CYTHON_UNUSED size_t __pyx_v_data_len, CYTHON_UNUSED void *__pyx_v_user_ptr) {
                 ^
    creating build/lib.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/uvc.o -lrt -luvc -lturbojpeg -o build/lib.linux-x86_64-3.5/uvc.cpython-35m-x86_64-linux-gnu.so
    /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
    /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a: error adding symbols: Bad value
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-_sxtiiuy-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-w_hs0c2t-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-_sxtiiuy-build/

**Comment by papr** [comment]
Important section: relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
... /libturbojpeg.a: error adding symbols: Bad value

**Comment by mkassner** [comment]
should this not be a .so lib?

**Comment by matiarj** [comment]
after trying to install on multiple machines with different version of 16.04.3 and 16.04.2 i finally figured this thing out...

the master commits for pyuvc and libuvc do NOT work....

i switched to commits made in February and they work after just  changing the version check to 0.10

File "/home/matiar/pupil/pupil_src/shared_modules/video_capture/uvc_backend.py", line 20, in <module>
    assert VersionFormat(uvc.__version__) >= VersionFormat('0.11')

i assume this is not safe moving forward but I think its important that the masters be fixed the main error i kept running into was python3 was unable to import uvc....

i urge you guys to test out the developer setup on a fresh ubuntu install because I nearly lost my mind.

**Comment by wjpjet** [comment]
I have the exact same error, using 16.04. Same error in docker builds. Running python 3.6.

I switched to your libuvc version and I tried your commit, I got the same error message. 

I switched to february commit (you chose a later march commit): pip install git+https://github.com/pupil-labs/pyuvc@c0c2f70ed5d61e2ae88e00e091c7262c8ed17303




I got this error: 

```Could not find a tag or branch 'c0c2f70ed5d61e2ae88e00e091c7262c8ed17303', assuming commit.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-4hihopdz-build/setup.py", line 33, in <module>
        tj_lib = glob.glob('/opt/libjpeg-turbo/lib*')[0]+'/libturbojpeg.a'
    IndexError: list index out of range
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-4hihopdz-build/setup.py", line 35, in <module>
        raise Exception("Please install libturbojpeg")
    Exception: Please install libturbojpeg
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-4hihopdz-build/```

**Comment by mkassner** [comment]
please remove any libturbojpeg.a and try again. We are using runtime libs (.so)
