### ISSUE TITLE
unable to receive uncompressed image frames directly from camera

### ISSUE THREAD

**Issue by camcse** [pupil-labs/pyuvc#37]
Hi - Is it possible to receive uncompressed (YUYV) image frames directly from cameras instead of converting MJPEG to YUV (jpeg2yuv)?

I have tried below changes in uvc.pyx

In _enumerate_formats()
frame_desc.bDescriptorSubtype == uvc.**UVC_VS_FRAME_UNCOMPRESSED**

status = uvc.**uvc_get_stream_ctrl_format_size**( self.devh, &self.ctrl, uvc.**UVC_FRAME_FORMAT_UNCOMPRESSED**, mode[0],mode[1],mode[2] )

In the received uvc_frame, frame_format(uvc_frame_format) is UVC_FRAME_FORMAT_YUYV which is correct but the frame dump shows it is still an mjpeg frame and jpeg2yuv call also succeeds. Please tell me what am I missing here.

OS - Windows 10, Cameras - USB cameras in Pupil ET addon for Oculus DK2
Camera Device Configuration file attached
[camera_configuration.txt](https://github.com/pupil-labs/pyuvc/files/1449009/camera_configuration.txt)

**Comment by mkassner** [comment]
This is not supported by pyuvc. There is a branch that does something smlr. https://github.com/pupil-labs/pyuvc/tree/yuv

**Comment by camcse** [comment]
Thanks for the tip. Did you check this on windows? I tried but did not succeed.

Executing example.py
  File "uvc.pyx", line 402, in uvc.Capture._start (uvc.c:10813)
    raise InitError("Can't start isochronous stream: Error:'%s'."%uvc_error_codes[status])
uvc.InitError

Running pupil_service.exe
eye0 - [WARNING] video_capture.uvc_backend: Capture failed to provide frames. Attempting to reinit.
eye1 - [WARNING] video_capture.uvc_backend: Capture failed to provide frames. Attempting to reinit.
