### ISSUE TITLE
can't install pyuvc

### ISSUE THREAD

**Issue by chalgand** [pupil-labs/pyuvc#41]
After installing libuvc from pupil-labs github, I can't install pyuvc 

> python3 setup.py install

`Compiling uvc.pyx because it changed.`
`[1/1] Cythonizing uvc.pyx`
`running install`
`running build`
`running build_ext`
`building 'uvc' extension`
`creating build`
`creating build/temp.macosx-10.13-x86_64-3.6`
`clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/lib/python3.6/site-packages/numpy/core/include -I/usr/local/opt/jpeg-turbo/include/ -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c uvc.c -o build/temp.macosx-10.13-x86_64-3.6/uvc.o
uvc.c:556:10: fatal error: 'libuvc/libuvc.h' file not found
#include "libuvc/libuvc.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
error: command 'clang' failed with exit status 1`

libuvc/libuvc.h is in 

> /Users/chalgand/libuvc/build/include

**Comment by mkassner** [comment]
make sure to install libuvc not just build it.
