### ISSUE TITLE
Could not get image reading from The Image Source camera

### ISSUE THREAD

**Issue by zhyzj1988** [pupil-labs/pyuvc#42]
Hi,

I am working on a project to build a stereo camera using two USB industrial cameras (Model DFK 33UX252, The Imaging Source). And I want to use the pyuvc to get the image from camera. However, I have some problems to read the image.

When I run "cap = uvc.Capture(dev_list[0]['uid'])", it appears the error:
_ERROR:uvc:Could not init 'White Balance temperature red'! Error: range() arg 3 must not be zero_
and the _cap.avaible_modes_ is none. So can not get the image.

I have also tried a webcam from logitech, and it works well.

Thanks so much!

**Comment by mkassner** [comment]
I bet this is your camera not being uvc compliant. You will have to make changes to the source.
