### ISSUE TITLE
pyuvc not compiled

### ISSUE THREAD

**Issue by waschbaer00** [pupil-labs/pyuvc#44]
I have pyhton 3.5, 16.04 Ubuntu system.

I have installed all dependencies required on this page https://github.com/pupil-labs/pyuvc

**I tried:**
sudo pip3 install git+https://github.com/pupil-labs/pyuvc

**I got following error:**

Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-ce0ft5xj-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-s5_yrcp6-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-ce0ft5xj-build/

**More details in log:**

Collecting git+https://github.com/pupil-labs/pyuvc
  Cloning https://github.com/pupil-labs/pyuvc to /tmp/pip-ce0ft5xj-build
Installing collected packages: uvc
  Running setup.py install for uvc ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-ce0ft5xj-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-s5_yrcp6-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'uvc' extension
    creating build
    creating build/temp.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/ics_vr/.local/lib/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -c uvc.c -o build/temp.linux-x86_64-3.5/uvc.o
    In file included from /home/ics_vr/.local/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1816:0,
                     from /home/ics_vr/.local/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /home/ics_vr/.local/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from uvc.c:555:
    /home/ics_vr/.local/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    uvc.c: In function ‘__pyx_f_3uvc_7Capture__enumerate_controls’:
    uvc.c:17423:26: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_input_terminal = uvc_get_input_terminals(__pyx_v_self->devh);
                              ^
    uvc.c:17432:27: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_output_terminal = uvc_get_output_terminals(__pyx_v_self->devh);
                               ^
    uvc.c:17441:27: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_processing_unit = uvc_get_processing_units(__pyx_v_self->devh);
                               ^
    uvc.c:17450:26: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_extension_unit = uvc_get_extension_units(__pyx_v_self->devh);
                              ^
    uvc.c: In function ‘__pyx_f_3uvc_7Capture__enumerate_formats’:
    uvc.c:18085:23: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_format_desc = uvc_get_format_descs(__pyx_v_self->devh);
                           ^
    uvc.c: At top level:
    uvc.c:20548:13: warning: ‘__pyx_f_3uvc_on_status_update’ defined but not used [-Wunused-function]
     static void __pyx_f_3uvc_on_status_update(CYTHON_UNUSED enum uvc_status_class __pyx_v_status_class, CYTHON_UNUSED int __pyx_v_event, CYTHON_UNUSED int __pyx_v_selector, CYTHON_UNUSED enum uvc_status_attribute __pyx_v_status_attribute, CYTHON_UNUSED void *__pyx_v_data, CYTHON_UNUSED size_t __pyx_v_data_len, CYTHON_UNUSED void *__pyx_v_user_ptr) {
                 ^
    creating build/lib.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/uvc.o -lrt -luvc -lturbojpeg -o build/lib.linux-x86_64-3.5/uvc.cpython-35m-x86_64-linux-gnu.so
    /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
    /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a: error adding symbols: Bad value
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-ce0ft5xj-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-s5_yrcp6-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-ce0ft5xj-build/

**Comment by papr** [comment]
> /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC

This means that you have a static turbojpeg lib installation. Please remove it and make sure to compile it dynamically:

> wget -O libjpeg-turbo.tar.gz https://sourceforge.net/projects/libjpeg-turbo/files/1.5.1/libjpeg-turbo-1.5.1.tar.gz/download
tar xvzf libjpeg-turbo.tar.gz
cd libjpeg-turbo-1.5.1
./configure **--enable-static=no** --prefix=/usr/local
sudo make install
sudo ldconfig

**Comment by waschbaer00** [comment]
When I run your command, I have following error message at the beginning of the log, but at the end, the log does not tell me whether there are issues during the installation. Could you help to check? Thank you.

libtool:   error: ignoring unknown tag NASM
  GEN      jccolor-sse2-64.lo

**Comment by papr** [comment]
Would you mind posting the complete log?

**Comment by waschbaer00** [comment]
After second time sudo make install, the error disappear.  And I still can not compile pyuvc.

Log for the second try with sudo make install:
=====================================
Making install in java
make[1]: Entering directory '/home/ics_vr/softwares/libjpeg-turbo-1.5.1/java'
make[2]: Entering directory '/home/ics_vr/softwares/libjpeg-turbo-1.5.1/java'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/ics_vr/softwares/libjpeg-turbo-1.5.1/java'
make[1]: Leaving directory '/home/ics_vr/softwares/libjpeg-turbo-1.5.1/java'
Making install in simd
make[1]: Entering directory '/home/ics_vr/softwares/libjpeg-turbo-1.5.1/simd'
make  install-am
make[2]: Entering directory '/home/ics_vr/softwares/libjpeg-turbo-1.5.1/simd'
make[3]: Entering directory '/home/ics_vr/softwares/libjpeg-turbo-1.5.1/simd'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/ics_vr/softwares/libjpeg-turbo-1.5.1/simd'
make[2]: Leaving directory '/home/ics_vr/softwares/libjpeg-turbo-1.5.1/simd'
make[1]: Leaving directory '/home/ics_vr/softwares/libjpeg-turbo-1.5.1/simd'
Making install in md5
make[1]: Entering directory '/home/ics_vr/softwares/libjpeg-turbo-1.5.1/md5'
make[2]: Entering directory '/home/ics_vr/softwares/libjpeg-turbo-1.5.1/md5'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/ics_vr/softwares/libjpeg-turbo-1.5.1/md5'
make[1]: Leaving directory '/home/ics_vr/softwares/libjpeg-turbo-1.5.1/md5'
make[1]: Entering directory '/home/ics_vr/softwares/libjpeg-turbo-1.5.1'
make[2]: Entering directory '/home/ics_vr/softwares/libjpeg-turbo-1.5.1'
 /bin/mkdir -p '/usr/local/lib'
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   libjpeg.la libturbojpeg.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libjpeg.so.62.2.0 /usr/local/lib/libjpeg.so.62.2.0
libtool: install: (cd /usr/local/lib && { ln -s -f libjpeg.so.62.2.0 libjpeg.so.62 || { rm -f libjpeg.so.62 && ln -s libjpeg.so.62.2.0 libjpeg.so.62; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libjpeg.so.62.2.0 libjpeg.so || { rm -f libjpeg.so && ln -s libjpeg.so.62.2.0 libjpeg.so; }; })
libtool: install: /usr/bin/install -c .libs/libjpeg.lai /usr/local/lib/libjpeg.la
libtool: install: /usr/bin/install -c .libs/libturbojpeg.so.0.1.0 /usr/local/lib/libturbojpeg.so.0.1.0
libtool: install: (cd /usr/local/lib && { ln -s -f libturbojpeg.so.0.1.0 libturbojpeg.so.0 || { rm -f libturbojpeg.so.0 && ln -s libturbojpeg.so.0.1.0 libturbojpeg.so.0; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libturbojpeg.so.0.1.0 libturbojpeg.so || { rm -f libturbojpeg.so && ln -s libturbojpeg.so.0.1.0 libturbojpeg.so; }; })
libtool: install: /usr/bin/install -c .libs/libturbojpeg.lai /usr/local/lib/libturbojpeg.la
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin" ldconfig -n /usr/local/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /usr/local/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /bin/mkdir -p '/usr/local/bin'
  /bin/bash ./libtool   --mode=install /usr/bin/install -c cjpeg djpeg jpegtran rdjpgcom wrjpgcom tjbench '/usr/local/bin'
libtool: install: /usr/bin/install -c .libs/cjpeg /usr/local/bin/cjpeg
libtool: install: /usr/bin/install -c .libs/djpeg /usr/local/bin/djpeg
libtool: install: /usr/bin/install -c .libs/jpegtran /usr/local/bin/jpegtran
libtool: install: /usr/bin/install -c .libs/rdjpgcom /usr/local/bin/rdjpgcom
libtool: install: /usr/bin/install -c .libs/wrjpgcom /usr/local/bin/wrjpgcom
libtool: install: /usr/bin/install -c .libs/tjbench /usr/local/bin/tjbench
 /bin/mkdir -p '/usr/local/share/doc/libjpeg-turbo'
 /usr/bin/install -c -m 644 README.ijg README.md libjpeg.txt structure.txt usage.txt wizard.txt LICENSE.md '/usr/local/share/doc/libjpeg-turbo'
 /bin/mkdir -p '/usr/local/share/doc/libjpeg-turbo'
 /usr/bin/install -c -m 644 example.c '/usr/local/share/doc/libjpeg-turbo'
 /bin/mkdir -p '/usr/local/include'
 /usr/bin/install -c -m 644 jerror.h jmorecfg.h jpeglib.h turbojpeg.h '/usr/local/include'
 /bin/mkdir -p '/usr/local/share/man/man1'
 /usr/bin/install -c -m 644 cjpeg.1 djpeg.1 jpegtran.1 rdjpgcom.1 wrjpgcom.1 '/usr/local/share/man/man1'
 /bin/mkdir -p '/usr/local/include'
 /usr/bin/install -c -m 644 jconfig.h '/usr/local/include'
 /bin/mkdir -p '/usr/local/lib/pkgconfig'
 /usr/bin/install -c -m 644 pkgscripts/libjpeg.pc pkgscripts/libturbojpeg.pc '/usr/local/lib/pkgconfig'
make[2]: Leaving directory '/home/ics_vr/softwares/libjpeg-turbo-1.5.1'
make[1]: Leaving directory '/home/ics_vr/softwares/libjpeg-turbo-1.5.1'

**Comment by papr** [comment]
What is the output if you run `ls -lh /usr/local/lib/libturbo*` in the terminal?
```
-rwxr-xr-x 1 root root  937 Nov 21 11:42 /usr/local/lib/libturbojpeg.la*
lrwxrwxrwx 1 root root   21 Nov 21 11:42 /usr/local/lib/libturbojpeg.so -> libturbojpeg.so.0.1.0*
lrwxrwxrwx 1 root root   21 Nov 21 11:42 /usr/local/lib/libturbojpeg.so.0 -> libturbojpeg.so.0.1.0*
-rwxr-xr-x 1 root root 635K Nov 21 11:42 /usr/local/lib/libturbojpeg.so.0.1.0*
```
Mine looks like above.

**Comment by waschbaer00** [comment]
-rwxr-xr-x 1 root root  937 Feb 27 16:03 /usr/local/lib/libturbojpeg.la
lrwxrwxrwx 1 root root   21 Feb 27 16:03 /usr/local/lib/libturbojpeg.so -> libturbojpeg.so.0.1.0
lrwxrwxrwx 1 root root   21 Feb 27 16:03 /usr/local/lib/libturbojpeg.so.0 -> libturbojpeg.so.0.1.0
-rwxr-xr-x 1 root root 651K Feb 27 16:03 /usr/local/lib/libturbojpeg.so.0.1.0

**Comment by papr** [comment]
Ok, this means that the installation was successful. Do not forget to run `sudo ldconfig` and re-try to install `pyuvc`.

**Comment by waschbaer00** [comment]
Still not compiled..

**Comment by papr** [comment]
Please post the log for the current build failure.

**Comment by waschbaer00** [comment]
sudo pip3 install git+https://github.com/pupil-labs/pyuvc


The directory '/home/ics_vr/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ics_vr/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+https://github.com/pupil-labs/pyuvc
  Cloning https://github.com/pupil-labs/pyuvc to /tmp/pip-p4bya21n-build
Installing collected packages: uvc
  Running setup.py install for uvc ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-p4bya21n-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-mk75ijve-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'uvc' extension
    creating build
    creating build/temp.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/ics_vr/.local/lib/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -c uvc.c -o build/temp.linux-x86_64-3.5/uvc.o
    In file included from /home/ics_vr/.local/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1816:0,
                     from /home/ics_vr/.local/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /home/ics_vr/.local/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from uvc.c:555:
    /home/ics_vr/.local/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    uvc.c: In function ‘__pyx_f_3uvc_7Capture__enumerate_controls’:
    uvc.c:17423:26: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_input_terminal = uvc_get_input_terminals(__pyx_v_self->devh);
                              ^
    uvc.c:17432:27: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_output_terminal = uvc_get_output_terminals(__pyx_v_self->devh);
                               ^
    uvc.c:17441:27: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_processing_unit = uvc_get_processing_units(__pyx_v_self->devh);
                               ^
    uvc.c:17450:26: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_extension_unit = uvc_get_extension_units(__pyx_v_self->devh);
                              ^
    uvc.c: In function ‘__pyx_f_3uvc_7Capture__enumerate_formats’:
    uvc.c:18085:23: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_format_desc = uvc_get_format_descs(__pyx_v_self->devh);
                           ^
    uvc.c: At top level:
    uvc.c:20548:13: warning: ‘__pyx_f_3uvc_on_status_update’ defined but not used [-Wunused-function]
     static void __pyx_f_3uvc_on_status_update(CYTHON_UNUSED enum uvc_status_class __pyx_v_status_class, CYTHON_UNUSED int __pyx_v_event, CYTHON_UNUSED int __pyx_v_selector, CYTHON_UNUSED enum uvc_status_attribute __pyx_v_status_attribute, CYTHON_UNUSED void *__pyx_v_data, CYTHON_UNUSED size_t __pyx_v_data_len, CYTHON_UNUSED void *__pyx_v_user_ptr) {
                 ^
    creating build/lib.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/uvc.o -lrt -luvc -lturbojpeg -o build/lib.linux-x86_64-3.5/uvc.cpython-35m-x86_64-linux-gnu.so
    /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
    /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a: error adding symbols: Bad value
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-p4bya21n-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-mk75ijve-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-p4bya21n-build/

**Comment by papr** [comment]
There is still a statically compiled libturbojpeg version present on you system
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a

Please try to find it and to delete it.

**Comment by papr** [comment]
What is the output for running `ls -lh /usr/lib/x86_64-linux-gnu/libturbo*` in your terminal?

**Comment by papr** [comment]
What is the output for running `ls -lh /usr/lib/x86_64-linux-gnu/libturbo*` in your terminal?

**Comment by waschbaer00** [comment]
-rw-r--r-- 1 root root 596K Feb 22  2016 /usr/lib/x86_64-linux-gnu/libturbojpeg.a

**Comment by waschbaer00** [comment]
should I delete /usr/lib/x86_64-linux-gnu/libturbojpeg.a? If I delete it should I reinstall libturbojpeg?

**Comment by papr** [comment]
Please run `sudo rm /usr/lib/x86_64-linux-gnu/libturbojpeg.a`. This will delete the static library. Rerun the pyuvc installation afterwards. If there are still issues please post the log.

**Comment by papr** [comment]
There is no need for reinstalling. Run `sudo ldconfig` before installing pyuvc to be sure. though.

**Comment by waschbaer00** [comment]
Yes! Doen!

Thank you for the reply and helps!

**Comment by waschbaer00** [comment]
One question more, why static library cause problem? I am beginner in Linux.

**Comment by papr** [comment]
This has something to do how libraries link to each other. Static and dynamic linking are just not compatible, as far as I know.

**Comment by waschbaer00** [comment]
Thank you.
