### ISSUE TITLE
ImportError after fresh install

### ISSUE THREAD

**Issue by maciejorlinski** [pupil-labs/pyuvc#45]
I've just installed pyuvc with all listed dependencies and I'm stuck at this error:

```Python 3.4.2 (default, Oct  8 2014, 13:14:40) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import uvc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/local/lib/libuvc.so.0: undefined symbol: libusb_handle_events_completed
```

I've already tried reinstalling libuvc but with no luck

**Comment by maciejorlinski** [comment]
sorry, it's a libusb issue

**Comment by kramachandran1980** [comment]
any luck on this?

**Comment by sayimvikash** [comment]
libuvc is not  properly linked with libusb because of missing pkg-config.
Install pkg configuration
  $ sudo apt-get install pkg-config
After installing it, build libuvc and then pyuvc
