### ISSUE TITLE
raise InitError("Can't open stream control: Error:'%s'."%uvc_error_codes[status])

### ISSUE THREAD

**Issue by ShuangjunLiu** [pupil-labs/pyuvc#51]
I followed exact step given for WINDOWS_USER. 
After ran the example, I got the error 

>     raise InitError("Can't open stream control: Error:'%s'."%uvc_error_codes[status])
> uvc.InitError

It showed correctly the dev_list and supported format. 
However, it won't open the stream. 

env:
windows 10 
python 3.6.3 
webcam: logitech c525

**Comment by willpatera** [comment]
@ShuangjunLiu please see #57 - I will close this issue. Please re-open or comment if you still can not resolve this.
