### ISSUE TITLE
Imposible to import uvc after having install it regarding README.md

### ISSUE THREAD

**Issue by valvador92** [pupil-labs/pyuvc#55]
I can't import uvc.
If I try to run from the terminal I have this error: ImportError: No module named uvc.

I installed libuvc and libjpeg-turbo like it is explained. Do I need to do anything else? Do I need to clone this repo? I am lost

I am using Python 2.7

Thank you

**Comment by valvador92** [comment]
I cloned this repo and compil the file uvc.pyx. But whe n I want to import it, I have this issue:
ImportError: ./uvc.so: undefined symbol: uvc_init.

Maybe I compiled it wrong. It is the first time I am using cython file.

Thank you

**Comment by mkassner** [comment]
These are dependencies issues. Make sure your build environment works.

**Comment by valvador92** [comment]
![screenshot from 2018-11-05 10-24-21](https://user-images.githubusercontent.com/33961158/47989570-a37fe280-e0e5-11e8-94b0-ad3c673bc581.png)

**Comment by willpatera** [comment]
According to #57 It looks like you were able to build pyuvc. I will close this issue. If you would like to follow up with notes on what you did to resolve the issue/behavior, it would be helpful for other users in the future.
