### ISSUE TITLE
"Can't get stream control: Error:'%s'."%uvc_error_codes[status]

### ISSUE THREAD

**Issue by valvador92** [pupil-labs/pyuvc#57]
![image](https://user-images.githubusercontent.com/33961158/48009178-6afafb80-e11b-11e8-8fad-caa0ffb4a2b1.png)

raise InitError("Can't get stream control: Error:'%s'."%uvc_error_codes[status])
uvc.InitError

I don't understand why I have this error when I run example.py
I have done the same installation on my Laptop, example.py is working with the integrated webcam,  but as soon I want to plug the Headset, I have this error.

I think that the error is coming from this command: frame = cap.get_frame_robust()

**Comment by willpatera** [comment]
It looks like you need to modify `example.py`. The example is trying to cap at resolution (640, 480) at 15 fps. However, if you see the list of available modes printed above you see that this is not an option. Please try (129, 192, 200) - or any of the other available modes - in https://github.com/pupil-labs/pyuvc/blob/master/example.py#L18.

**Comment by valvador92** [comment]
It works with (192,192,120) for the eye cameras and (1280,720,30) for the world camera.
Thank you!

Now, how to show the images in rgb? For now it is only in gray.

I can't find a command in OpenCV for that

**Comment by papr** [comment]
The eye cameras record in the ir light spectrum. Color values are not meaningful in that space.

**Comment by valvador92** [comment]
Yeah I know. But for the World camera, how can I do it?

**Comment by valvador92** [comment]
I have found the answer: it is frame.bgr to show the picture un RGB

**Comment by willpatera** [comment]
Hi @valvador92 I will close this issue now as it seems to be resolved for you. Please re-open or comment if not.
