### ISSUE TITLE
Typo in Property Name

### ISSUE THREAD

**Issue by yurikleb** [pupil-labs/pyuvc#77]
There is a typo in the "available_modes" property name:
https://github.com/pupil-labs/pyuvc/blob/c16f2c8e5b0db2d52bd2ce6861a4c905cb34d9ba/uvc.pyx#L748
it says "avaible" - "la" is missing.

Which can lead to a few very long minutes of debugging if you dont just copy-paste from the example file or using autocomplete :)

**Comment by papr** [comment]
@yurikleb Thank you very much for reporting this. We will add a correctly spelled version of the property while keeping the old one for backward compatibility.

**Comment by yurikleb** [comment]
sounds good thanks!
