### ISSUE TITLE
Windows: Some runtime dependencies are missing

### ISSUE THREAD

**Issue by skywu** [pupil-labs/pyuvc#84]
I have executed setup.py and it seems to be installed smoothly.
```
...
Installed f:\pyuvc\venv\lib\site-packages\uvc-0.14-py3.9-win-amd64.egg
Processing dependencies for uvc==0.14
Searching for numpy==1.20.2
Best match: numpy 1.20.2
Adding numpy 1.20.2 to easy-install.pth file
Installing f2py-script.py script to F:\pyuvc\venv\Scripts
Installing f2py.exe script to F:\pyuvc\venv\Scripts

Using f:\pyuvc\venv\lib\site-packages
Finished processing dependencies for uvc==0.14

```
But when example.py is executed, the following error message appears:

```
Traceback (most recent call last):
  File "F:\pyuvc\example.py", line 2, in <module>
    import uvc
ImportError: DLL load failed while importing uvc: Cannot find the specified module。
```

The libusb and libuvc libraries I compiled are vs2019 x64 projects,Trying to install vc_redist.x64.exe also did not solve my problem.
Confused..., who encountered this problem and how to solve it?

**Comment by papr** [comment]
Hi, please use https://github.com/lucasg/Dependencies on the `f:\pyuvc\venv\lib\site-packages\uvc*.pyd` file (I think the fle extension is `pyd`, not 100% sure) to check which dependency is missing. My guess is that libturbojpeg is missing.

**Comment by skywu** [comment]
@papr thank you for your reply
