### ISSUE TITLE
Can't install libjpeg-turbo-1.5.1 on ubuntu 20.04.4 LTS

### ISSUE THREAD

**Issue by yurikleb** [pupil-labs/pyuvc#89]
I'm unable to install libjpeg-turbo on Ubuntu 20.04.4
I'm geting an `configure: error: no nasm (Netwide Assembler) found` error 
when trying to run the `./configure --with-pic --prefix=/usr/local` command.

It seems like this issue is solved on later versions as discussed here: https://www.illumos.org/issues/11899
Is it possible to update the instructions in the readme?

**Comment by yurikleb** [comment]
I installed libjpeg-turbo-2.1.4 following the instructions here:
https://www.linuxfromscratch.org/blfs/view/svn/general/libjpeg.html

And then managed to install PYUVC.

**Comment by papr** [comment]
Alternatively, run `apt-get install nasm` before building.

We are working on a new release with easier install instructions
